# make
[[lines]]
	pat = "^make\\[\\w*\\]: ((Entering|Leaving) directory .*)"
	colors = ["Default", "Magenta"]
	tokens = []

# CMake build
[[lines]]
	pat = "^Scanning dependencies of target .*"
	colors = ["Cyan"]
	tokens = []
[[lines]]
	pat = "^\\[[0-9 ]+%\\] (Building C(XX)? object) .*"
	colors = ["Default", "LightGreen"]
	tokens = []
[[lines]]
	pat = "^\\[[0-9 ]+%\\] (Linking C(XX)? ((static|shared) library|executable)) .*"
	colors = ["Default", "LightGreen"]
	tokens = []
[[lines]]
	pat = "^\\[[0-9 ]+%\\] (Built target .*)"
	colors = ["Default", "LightGreen"]
	tokens = []

# CXX / GTest
[[lines]]
	pat = "^(\\S+):(\\d+):"
	colors = ["Default", "Magenta", "Green"]
	[[lines.tokens]]
		pat = " Failure"
		colors = ["LightRed"]
	[[lines.tokens]]
		pat = " error"
		colors = ["LightRed"]
	[[lines.tokens]]
		pat = " warning"
		colors = ["LightYellow"]
	[[lines.tokens]]
		pat = " note"
		colors = ["LightCyan"]
	[[lines.tokens]]
		pat = " tried expectation( #\\d+)?"
		colors = ["Cyan"]
[[lines]]
	pat = "^(unknown file):"
	colors = ["Default", "Magenta"]
	[[lines.tokens]]
		pat = " Failure"
		colors = ["LightRed"]
	[[lines.tokens]]
		pat = " error"
		colors = ["LightRed"]
	[[lines.tokens]]
		pat = " warning"
		colors = ["LightYellow"]
	[[lines.tokens]]
		pat = " note"
		colors = ["LightCyan"]
	[[lines.tokens]]
		pat = " tried expectation( #\\d+)?"
		colors = ["Cyan"]
[[lines]]
	pat = "^[[:space:]]*(Function call|Actual):"
	colors = ["Default", "LightRed"]
	[[lines.tokens]]
		pat = " unsatisfied"
		colors = ["Red"]
	[[lines.tokens]]
		pat = " saturated"
		colors = ["Green"]
	[[lines.tokens]]
		pat = " over-saturated"
		colors = ["Yellow"]
[[lines]]
	pat = "^[[:space:]]*(Expected( arg #\\d+)?):"
	colors = ["Default", "LightCyan"]
	tokens = []
[[lines]]
	pat = "^\\[.{10}\\].*"
	colors = ["Default"]
	[[lines.tokens]]
		pat = "\\[ RUN      \\]|\\[       OK \\]"
		colors = ["LightGreen"]
	[[lines.tokens]]
		pat = "\\[  FAILED  \\]"
		colors = ["LightRed"]
	[[lines.tokens]]
		pat = "\\[----------\\]"
		colors = ["LightCyan"]
	[[lines.tokens]]
		pat = "\\[==========\\]"
		colors = ["LightBlue"]
[[lines]]
	pat = "^\\s*\\d+ FAILED TESTS"
	colors = ["LightYellow"]
	tokens = []
